# Generated by Django 3.2.12 on 2022-06-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modevariant',
            name='meta',
            field=models.JSONField(null=True),
        ),
    ]
