# Generated by Django 4.2 on 2023-04-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0002_matrix_partitioning'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['room', 'level', 'date'], name='datentool_b_room_30fee0_idx'),
        ),
    ]
