# Generated by Django 3.2.4 on 2021-08-17 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0002_auto_20210730_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agegroup',
            name='from_age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(127)]),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='to_age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(127)]),
        ),
        migrations.AlterField(
            model_name='rastercell',
            name='cellcode',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(12)]),
        ),
    ]
