# Generated by Django 3.2.12 on 2022-06-10 12:04

import datentool_backend.base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0002_alter_modevariant_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('network_file', models.FileField(null=True, upload_to='')),
            ],
            bases=(datentool_backend.base.NamedModel, models.Model),
        ),
        migrations.RemoveField(
            model_name='modevariant',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='modevariant',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='modevariant',
            name='name',
        ),
        migrations.AddField(
            model_name='modevariant',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.network'),
        ),
    ]
