# Generated by Django 3.2.12 on 2022-08-10 14:54

import datentool_backend.utils.protect_cascade
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0003_auto_20220610_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='modevariant',
            name='label',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='stop',
            name='hstnr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stop',
            name='variant',
            field=models.ForeignKey(default=0, on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.modevariant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterUniqueTogether(
            name='stop',
            unique_together={('variant', 'hstnr')},
        ),
    ]
