# Generated by Django 3.2.5 on 2021-07-14 21:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0003_auto_20210714_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='layer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.internalwfslayer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='symbol',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.mapsymbols'),
            preserve_default=False,
        ),
    ]
