# Generated by Django 4.2 on 2023-09-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0003_logentry_datentool_b_room_30fee0_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_demo_user',
            field=models.BooleanField(default=False),
        ),
    ]
