# Generated by Django 3.2.5 on 2021-09-01 22:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0004_disaggpopraster_raster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rastercell',
            name='cellcode',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(13)]),
        ),
    ]
