# Generated by Django 3.2.5 on 2021-07-14 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0004_auto_20210714_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_age', models.IntegerField()),
                ('to_age', models.IntegerField()),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.ageclassification')),
            ],
        ),
        migrations.CreateModel(
            name='DisaggPopRaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_level', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.arealevel')),
                ('genders', models.ManyToManyField(to='datentool_backend.Gender')),
                ('raster', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.disaggpopraster')),
            ],
        ),
        migrations.CreateModel(
            name='Prognosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('is_default', models.BooleanField()),
                ('age_classification', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.ageclassification')),
                ('raster', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.disaggpopraster')),
            ],
        ),
        migrations.CreateModel(
            name='Raster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RasterCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellcode', models.TextField()),
                ('value', models.FloatField()),
                ('raster', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.raster')),
            ],
        ),
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RasterPopulationCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('age', models.IntegerField()),
                ('value', models.FloatField()),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.rastercell')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.gender')),
                ('raster', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.disaggpopraster')),
            ],
        ),
        migrations.AddField(
            model_name='raster',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.years'),
        ),
        migrations.CreateModel(
            name='PrognosisEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('agegroup', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.agegroup')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.area')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.gender')),
                ('prognosis', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.prognosis')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.years')),
            ],
        ),
        migrations.AddField(
            model_name='prognosis',
            name='years',
            field=models.ManyToManyField(to='datentool_backend.Years'),
        ),
        migrations.CreateModel(
            name='PopulationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.area')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.gender')),
                ('population', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.population')),
            ],
        ),
        migrations.AddField(
            model_name='population',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.years'),
        ),
        migrations.CreateModel(
            name='PopStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.years')),
            ],
        ),
        migrations.CreateModel(
            name='PopStatEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('immigration', models.FloatField()),
                ('emigration', models.FloatField()),
                ('births', models.FloatField()),
                ('deaths', models.FloatField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.area')),
                ('popstatistic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.popstatistic')),
            ],
        ),
        migrations.AddField(
            model_name='disaggpopraster',
            name='genders',
            field=models.ManyToManyField(to='datentool_backend.Gender'),
        ),
    ]
