# Generated by Django 4.2.6 on 2023-11-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0004_profile_is_demo_user'),
        ('datentool_backend', '0004_wmslayer_cors'),
    ]

    operations = [
    ]
