# Generated by Django 3.2.11 on 2022-08-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0004_auto_20220810_1654'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matrixcellplace',
            unique_together={('variant', 'cell', 'place')},
        ),
        migrations.AlterUniqueTogether(
            name='matrixcellstop',
            unique_together={('variant', 'cell', 'stop')},
        ),
        migrations.AlterUniqueTogether(
            name='matrixplacestop',
            unique_together={('variant', 'place', 'stop')},
        ),
        migrations.AlterUniqueTogether(
            name='matrixstopstop',
            unique_together={('variant', 'from_stop', 'to_stop')},
        ),
    ]
