# Generated by Django 3.2.5 on 2021-07-14 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0005_auto_20210715_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('meta', models.JSONField()),
                ('is_default', models.BooleanField()),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.modes')),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('osm_file', models.TextField()),
                ('tiff_file', models.TextField()),
                ('gtfs_file', models.TextField()),
                ('build_date', models.DateField()),
                ('buffer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReachabilityMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.FloatField()),
                ('from_cell', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='from_cell', to='datentool_backend.rastercell')),
                ('to_cell', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='to_cell', to='datentool_backend.rastercell')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.modevariant')),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(choices=[('T1', 'Type1'), ('T2', 'Type2')], max_length=2)),
                ('name', models.TextField()),
                ('parameters', models.JSONField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.service')),
            ],
        ),
    ]
