# Generated by Django 3.2.11 on 2022-08-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0005_auto_20220812_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areacell',
            old_name='cell',
            new_name='rastercellpop',
        ),
    ]
