# Generated by Django 3.2.5 on 2021-09-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0005_alter_rastercell_cellcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='years',
            name='bm_create_uuid',
            field=models.UUIDField(db_index=True, default=None, null=True),
        ),
    ]
