# Generated by Django 3.2.15 on 2022-08-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0006_rename_cell_areacell_rastercellpop'),
    ]

    operations = [
        migrations.AddField(
            model_name='modevariant',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
