# Generated by Django 3.2.6 on 2021-09-29 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0007_rename_attribure_placefield_attribute'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MapSymbols',
            new_name='MapSymbol',
        ),
    ]
