# Generated by Django 3.2.6 on 2021-09-29 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0008_rename_mapsymbols_mapsymbol'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Years',
            new_name='Year',
        ),
    ]
