# Generated by Django 4.1 on 2022-08-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0008_alter_scenariomode_scenario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modevariant',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
