# Generated by Django 3.2.6 on 2021-09-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0009_rename_years_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteSettings',
            new_name='SiteSetting',
        ),
    ]
