# Generated by Django 4.1 on 2022-09-02 15:53

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0009_alter_modevariant_is_default'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='placefield',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='placefield',
            constraint=models.UniqueConstraint(models.F('infrastructure'), django.db.models.functions.text.Lower('name'), name='unique_infra_field_name_lower_constraint'),
        ),
        migrations.AddConstraint(
            model_name='placefield',
            constraint=models.UniqueConstraint(models.F('infrastructure'), models.F('is_label'), name='unique_infra_field_is_label_constraint'),
        ),
    ]
