# Generated by Django 4.1 on 2022-09-06 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0010_alter_placefield_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.place'),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.scenario'),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.service'),
        ),
    ]
