# Generated by Django 3.2.6 on 2021-09-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0010_rename_sitesettings_sitesetting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modes',
            new_name='Mode',
        ),
    ]
