# Generated by Django 4.1 on 2022-09-07 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0011_alter_capacity_place_alter_capacity_scenario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixcellplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_cell', to='datentool_backend.place'),
        ),
        migrations.AlterField(
            model_name='matrixcellplace',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.modevariant'),
        ),
    ]
