# Generated by Django 3.2.6 on 2021-09-30 17:26

import datentool_backend.base
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.gis.geos import Point, Polygon


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0011_rename_modes_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationRaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('default', models.BooleanField(default=False)),
                ('raster', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.raster')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.year')),
            ],
            bases=(datentool_backend.base.NamedModel, models.Model),
        ),
        migrations.RenameModel(
            old_name='RasterPopulationCell',
            new_name='RasterCellPopulationAgeGender',
        ),
        migrations.RemoveField(
            model_name='rastercell',
            name='value',
        ),
        migrations.AddField(
            model_name='rastercell',
            name='pnt',
            field=django.contrib.gis.db.models.fields.PointField(default=Point(0, 0), srid=4326),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rastercell',
            name='poly',
            field=django.contrib.gis.db.models.fields.PolygonField(default=Polygon((Point(0, 0), Point(0, 10), Point(5, 5), Point(0, 0))), srid=4326),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RasterCellPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.rastercell')),
                ('raster', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.populationraster')),
            ],
        ),
        migrations.AlterField(
            model_name='disaggpopraster',
            name='raster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='datentool_backend.populationraster'),
        ),
    ]
