# Generated by Django 3.2.6 on 2021-09-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0012_auto_20210930_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raster',
            name='year',
        ),
    ]
