# Generated by Django 4.1 on 2022-09-12 10:12

import datentool_backend.base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0012_alter_matrixcellplace_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('room', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.profile')),
            ],
            bases=(datentool_backend.base.NamedModel, models.Model),
        ),
        migrations.RemoveField(
            model_name='capacityuploadlog',
            name='service',
        ),
        migrations.RemoveField(
            model_name='capacityuploadlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='placeuploadlog',
            name='infrastructure',
        ),
        migrations.RemoveField(
            model_name='placeuploadlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='AreaUploadLog',
        ),
        migrations.DeleteModel(
            name='CapacityUploadLog',
        ),
        migrations.DeleteModel(
            name='PlaceUploadLog',
        ),
    ]
