# Generated by Django 4.1 on 2022-10-10 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datentool_backend', '0013_logentry_remove_capacityuploadlog_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datentool_backend.profile'),
        ),
        migrations.CreateModel(
            name='ProcessState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.IntegerField(choices=[(1, 'Allgemein'), (2, 'Bevölkerung'), (3, 'Infrastruktur'), (4, 'Routing'), (5, 'Gebiete')])),
                ('is_running', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
