# Generated by Django 3.2.6 on 2021-09-30 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0013_remove_raster_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rastercellpopulation',
            old_name='raster',
            new_name='popraster',
        ),
    ]
