# Generated by Django 3.2.6 on 2021-09-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0014_rename_raster_rastercellpopulation_popraster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disaggpopraster',
            old_name='raster',
            new_name='popraster',
        ),
    ]
