# Generated by Django 3.2.6 on 2021-09-30 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0015_rename_raster_disaggpopraster_popraster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rastercellpopulationagegender',
            old_name='raster',
            new_name='disaggraster',
        ),
    ]
