# Generated by Django 4.1.2 on 2022-10-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0015_alter_place_infrastructure_alter_place_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningprocess',
            name='infrastructures',
            field=models.ManyToManyField(blank=True, related_name='processes', to='datentool_backend.infrastructure'),
        ),
    ]
