# Generated by Django 4.1.2 on 2022-10-18 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0016_planningprocess_infrastructures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='planning_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.planningprocess'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='prognosis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datentool_backend.prognosis'),
        ),
    ]
