# Generated by Django 4.1.2 on 2022-10-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datentool_backend", "0017_alter_scenario_planning_process_and_more"),
    ]

    operations = [
        migrations.RunSQL('''UPDATE datentool_backend_fclass f
SET "order" = r.rn FROM
(SELECT f.id,
row_number() OVER(PARTITION BY f.ftype_id ORDER BY f."order") AS rn
FROM datentool_backend_fclass f) r
WHERE f.id = r.id'''
                          ),
        migrations.AlterUniqueTogether(
            name="fclass", unique_together={("ftype", "order")},
        ),
    ]
