# Generated by Django 3.2.8 on 2021-11-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0017_demandrate_demandrateset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fclass',
            name='order',
            field=models.IntegerField(),
        ),
    ]
