# Generated by Django 4.1.2 on 2022-10-18 19:08

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ("datentool_backend", "0018_alter_fclass_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="fclass", unique_together=set(),),
        migrations.AddConstraint(
            model_name="fclass",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("ftype", "order"),
                name="fclass_unique",
            ),
        ),
    ]
