# Generated by Django 3.2.8 on 2021-11-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0018_alter_fclass_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='accessible_by',
            field=models.ManyToManyField(blank=True, related_name='infrastructure_accessible_by', to='datentool_backend.Profile'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='editable_by',
            field=models.ManyToManyField(blank=True, related_name='infrastructure_editable_by', to='datentool_backend.Profile'),
        ),
    ]
