# Generated by Django 4.1.2 on 2022-10-26 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0019_alter_fclass_unique_together_fclass_fclass_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutofftime',
            name='mode_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.modevariant'),
        ),
        migrations.AlterField(
            model_name='matrixcellstop',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.modevariant'),
        ),
        migrations.AlterField(
            model_name='matrixplacestop',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.modevariant'),
        ),
        migrations.AlterField(
            model_name='matrixstopstop',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.modevariant'),
        ),
        migrations.AlterField(
            model_name='scenariomode',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.modevariant'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.modevariant'),
        ),
    ]
