# Generated by Django 4.1.2 on 2022-11-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0020_alter_cutofftime_mode_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placefield',
            name='is_preset',
            field=models.BooleanField(default=False),
        ),
    ]
