# Generated by Django 3.2.8 on 2021-11-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0021_auto_20211129_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populationentry',
            name='age',
            field=models.IntegerField(default=41),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='shared_with_users', to='datentool_backend.Profile'),
        ),
    ]
