# Generated by Django 4.1.2 on 2022-11-01 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0021_placefield_is_preset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutofftime',
            name='infrastructure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.infrastructure'),
        ),
        migrations.AlterField(
            model_name='placefield',
            name='infrastructure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.infrastructure'),
        ),
        migrations.AlterField(
            model_name='service',
            name='infrastructure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.infrastructure'),
        ),
    ]
