# Generated by Django 4.1.1 on 2022-11-08 20:26

import datentool_backend.indicators.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('datentool_backend', '0022_alter_cutofftime_infrastructure_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matrixcellplace',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='matrixcellstop',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='matrixplacestop',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='matrixcellplace',
            name='access_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_access_variant', to='datentool_backend.modevariant'),
        ),
        migrations.AddField(
            model_name='matrixcellstop',
            name='access_variant',
            field=models.ForeignKey(default=datentool_backend.indicators.models.get_default_access_variant, on_delete=django.db.models.deletion.CASCADE, related_name='mcs_access_variant', to='datentool_backend.modevariant'),
        ),
        migrations.AddField(
            model_name='matrixplacestop',
            name='access_variant',
            field=models.ForeignKey(default=datentool_backend.indicators.models.get_default_access_variant, on_delete=django.db.models.deletion.CASCADE, related_name='mps_access_variant', to='datentool_backend.modevariant'),
        ),
        migrations.AlterField(
            model_name='matrixstopstop',
            name='variant',
            field=models.ForeignKey(default=datentool_backend.indicators.models.get_default_transit_variant, on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.modevariant'),
        ),
        migrations.AlterUniqueTogether(
            name='matrixcellplace',
            unique_together={('variant', 'access_variant', 'cell', 'place')},
        ),
        migrations.AddConstraint(
            model_name='matrixcellplace',
            constraint=models.UniqueConstraint(fields=('variant', 'access_variant', 'cell', 'place'), name='variant_accessvariant_cell_place_uniq'),
        ),
        migrations.AddConstraint(
            model_name='matrixcellplace',
            constraint=models.UniqueConstraint(condition=models.Q(('access_variant__isnull', True)), fields=('variant', 'cell', 'place'), name='variant_noaccessvariant_cell_place_uniq'),
        ),
        migrations.RemoveField(
            model_name='matrixcellstop',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='matrixplacestop',
            name='variant',
        ),
    ]
