# Generated by Django 3.2.6 on 2021-11-30 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0022_auto_20211130_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='can_edit_data',
            new_name='can_edit_basedata',
        ),
    ]
