# Generated by Django 3.2.8 on 2021-11-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0022_auto_20211130_1434'),
        ('datentool_backend', '0023_rename_can_edit_data_profile_can_edit_basedata'),
    ]

    operations = [
    ]
