# Generated by Django 3.2.8 on 2021-12-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0024_merge_20211130_1440'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='PlanningProcess',
        ),
    ]
