# Generated by Django 3.2.4 on 2021-12-02 17:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0024_merge_20211130_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_area', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('start_year', models.IntegerField(default=2000)),
                ('end_year', models.IntegerField(default=2020)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaseDataSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_pop_area_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datentool_backend.arealevel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
