# Generated by Django 4.1.1 on 2022-11-13 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0024_matrixcellstop_variant_matrixplacestop_variant_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matrixcellstop',
            unique_together={('access_variant', 'cell', 'stop')},
        ),
        migrations.AlterUniqueTogether(
            name='matrixplacestop',
            unique_together={('access_variant', 'place', 'stop')},
        ),
        migrations.AlterUniqueTogether(
            name='matrixstopstop',
            unique_together={('from_stop', 'to_stop')},
        ),
        migrations.RemoveField(
            model_name='matrixcellstop',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='matrixplacestop',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='matrixstopstop',
            name='variant',
        ),
    ]
