# Generated by Django 4.1.2 on 2022-11-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0025_alter_matrixcellstop_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placefield',
            name='label',
            field=models.TextField(blank=True, default=''),
        ),
    ]
