# Generated by Django 3.2.8 on 2021-12-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0025_rename_project_planningprocess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='can_create_project',
            new_name='can_create_process',
        ),
    ]
