# Generated by Django 3.2.8 on 2021-12-06 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0026_rename_can_create_project_profile_can_create_process'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='project',
            new_name='planning_process',
        ),
    ]
