# Generated by Django 4.1.2 on 2022-11-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0026_placefield_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='status',
            field=models.JSONField(null=True),
        ),
    ]
