# Generated by Django 3.2.8 on 2021-12-06 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0027_merge_20211206_1341'),
        ('datentool_backend', '0027_rename_project_scenario_planning_process'),
    ]

    operations = [
    ]
