# Generated by Django 4.1.3 on 2022-12-09 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0027_logentry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningprocess',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.profile'),
        ),
    ]
