# Generated by Django 3.2 on 2021-12-08 10:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0027_merge_20211206_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='project',
            new_name='planning_process',
        ),
        migrations.AlterField(
            model_name='projectsetting',
            name='project_area',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=25832),
        ),
    ]
