# Generated by Django 3.2.8 on 2021-12-07 14:10

import datentool_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0028_merge_20211206_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegStatAgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(datentool_backend.base.NamedModel, models.Model),
        ),
        migrations.RemoveField(
            model_name='agegroup',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='demandrateset',
            name='age_classification',
        ),
        migrations.RemoveField(
            model_name='prognosis',
            name='age_classification',
        ),
        migrations.DeleteModel(
            name='AgeClassification',
        ),
    ]
