# Generated by Django 4.1.4 on 2022-12-28 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0029_alter_stop_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeVariantStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_rels_place_cell', models.IntegerField(null=True)),
                ('n_rels_place_stop', models.IntegerField(null=True)),
                ('n_rels_stop_cell', models.IntegerField(null=True)),
                ('n_rels_stop_stop', models.IntegerField(null=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.modevariant')),
            ],
        ),
    ]
