# Generated by Django 3.2.8 on 2021-12-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0029_auto_20211207_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegStatAgeGroup',
        ),
    ]
