# Generated by Django 4.1.3 on 2023-01-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0030_modevariantstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsetting',
            name='project_net_date',
            field=models.DateTimeField(null=True),
        ),
    ]
