# Generated by Django 3.2.6 on 2021-12-08 18:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0030_delete_regstatagegroup'),
    ]
    geom_column = 'map_section'
    operations = [
        migrations.RunSQL(
            f"ALTER TABLE datentool_backend_planningprocess ALTER COLUMN {geom_column} type geometry(MultiPolygon, 4326) using ST_Multi({geom_column});",
            state_operations=[
                migrations.AlterField(
                    model_name='planningprocess',
                    name=geom_column,
                    field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
    ]
