# Generated by Django 3.2.6 on 2021-12-09 09:53

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0032_auto_20211209_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='place',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='projectsetting',
            name='project_area',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='rastercell',
            name='pnt',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='rastercell',
            name='poly',
            field=django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326),
        ),
    ]
