# Generated by Django 3.2 on 2021-12-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0037_auto_20211228_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalwfslayer',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='layergroup',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wmslayer',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
