# Generated by Django 3.2 on 2021-12-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0038_auto_20211229_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsymbol',
            name='symbol',
            field=models.CharField(choices=[('line', 'Line'), ('circle', 'Circle'), ('square', 'Square'), ('star', 'Star')], default='circle', max_length=9),
        ),
    ]
