# Generated by Django 3.2.6 on 2022-01-11 16:07

import datentool_backend.utils.protect_cascade
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0040_auto_20220104_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='planning_process',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.planningprocess'),
        ),
    ]
