# Generated by Django 3.2.4 on 2022-01-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0040_layergroup_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalwfslayer',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='wmslayer',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
