# Generated by Django 3.2.4 on 2022-01-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0041_auto_20220107_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalwfslayer',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wmslayer',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
