# Generated by Django 3.2.6 on 2022-01-11 20:02

import datentool_backend.utils.protect_cascade
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0041_alter_scenario_planning_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='bm_create_uuid',
        ),
        migrations.AlterField(
            model_name='area',
            name='area_level',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.arealevel'),
        ),
        migrations.AlterField(
            model_name='arealevel',
            name='layer',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.internalwfslayer'),
        ),
        migrations.AlterField(
            model_name='arealevel',
            name='source',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.source'),
        ),
        migrations.AlterField(
            model_name='areauploadlog',
            name='level',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.arealevel'),
        ),
        migrations.AlterField(
            model_name='areauploadlog',
            name='user',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.profile'),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='place',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.place'),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='service',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.service'),
        ),
        migrations.AlterField(
            model_name='capacityuploadlog',
            name='service',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.service'),
        ),
        migrations.AlterField(
            model_name='capacityuploadlog',
            name='user',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.profile'),
        ),
        migrations.AlterField(
            model_name='cutofftime',
            name='infrastructure',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.infrastructure'),
        ),
        migrations.AlterField(
            model_name='cutofftime',
            name='mode_variant',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.modevariant'),
        ),
        migrations.AlterField(
            model_name='demandrate',
            name='age_group',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.agegroup'),
        ),
        migrations.AlterField(
            model_name='demandrate',
            name='demand_rate_set',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.demandrateset'),
        ),
        migrations.AlterField(
            model_name='demandrate',
            name='year',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.year'),
        ),
        migrations.AlterField(
            model_name='demandrateset',
            name='service',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.service'),
        ),
        migrations.AlterField(
            model_name='disaggpopraster',
            name='popraster',
            field=models.ForeignKey(null=True, on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.populationraster'),
        ),
        migrations.AlterField(
            model_name='fclass',
            name='classification',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.fieldtype'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='service',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.service'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='layer',
            field=models.OneToOneField(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.internalwfslayer'),
        ),
        migrations.AlterField(
            model_name='internalwfslayer',
            name='group',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.layergroup'),
        ),
        migrations.AlterField(
            model_name='internalwfslayer',
            name='symbol',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.mapsymbol'),
        ),
        migrations.AlterField(
            model_name='matrixcellplace',
            name='cell',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, related_name='cell_place', to='datentool_backend.rastercell'),
        ),
        migrations.AlterField(
            model_name='matrixcellplace',
            name='place',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, related_name='place_cell', to='datentool_backend.place'),
        ),
        migrations.AlterField(
            model_name='matrixcellplace',
            name='variant',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.modevariant'),
        ),
        migrations.AlterField(
            model_name='matrixcellstop',
            name='cell',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, related_name='cell_stop', to='datentool_backend.rastercell'),
        ),
        migrations.AlterField(
            model_name='matrixcellstop',
            name='stop',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, related_name='stop_cell', to='datentool_backend.stop'),
        ),
        migrations.AlterField(
            model_name='matrixcellstop',
            name='variant',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.modevariant'),
        ),
        migrations.AlterField(
            model_name='matrixplacestop',
            name='place',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, related_name='place_stop', to='datentool_backend.place'),
        ),
        migrations.AlterField(
            model_name='matrixplacestop',
            name='stop',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, related_name='stop_place', to='datentool_backend.stop'),
        ),
        migrations.AlterField(
            model_name='matrixplacestop',
            name='variant',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.modevariant'),
        ),
        migrations.AlterField(
            model_name='matrixstopstop',
            name='from_stop',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, related_name='from_stop', to='datentool_backend.stop'),
        ),
        migrations.AlterField(
            model_name='matrixstopstop',
            name='to_stop',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, related_name='to_stop', to='datentool_backend.stop'),
        ),
        migrations.AlterField(
            model_name='matrixstopstop',
            name='variant',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.modevariant'),
        ),
        migrations.AlterField(
            model_name='modevariant',
            name='mode',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.mode'),
        ),
        migrations.AlterField(
            model_name='place',
            name='infrastructure',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.infrastructure'),
        ),
        migrations.AlterField(
            model_name='placefield',
            name='field_type',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.fieldtype'),
        ),
        migrations.AlterField(
            model_name='placefield',
            name='infrastructure',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.infrastructure'),
        ),
        migrations.AlterField(
            model_name='placeuploadlog',
            name='infrastructure',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.infrastructure'),
        ),
        migrations.AlterField(
            model_name='placeuploadlog',
            name='user',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.profile'),
        ),
        migrations.AlterField(
            model_name='popstatentry',
            name='area',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.area'),
        ),
        migrations.AlterField(
            model_name='popstatentry',
            name='popstatistic',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.popstatistic'),
        ),
        migrations.AlterField(
            model_name='popstatistic',
            name='year',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.year'),
        ),
        migrations.AlterField(
            model_name='population',
            name='area_level',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.arealevel'),
        ),
        migrations.AlterField(
            model_name='population',
            name='raster',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.disaggpopraster'),
        ),
        migrations.AlterField(
            model_name='population',
            name='year',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.year'),
        ),
        migrations.AlterField(
            model_name='populationentry',
            name='area',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.area'),
        ),
        migrations.AlterField(
            model_name='populationentry',
            name='gender',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.gender'),
        ),
        migrations.AlterField(
            model_name='populationentry',
            name='population',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.population'),
        ),
        migrations.AlterField(
            model_name='populationraster',
            name='raster',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.raster'),
        ),
        migrations.AlterField(
            model_name='populationraster',
            name='year',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.year'),
        ),
        migrations.AlterField(
            model_name='prognosisentry',
            name='agegroup',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.agegroup'),
        ),
        migrations.AlterField(
            model_name='prognosisentry',
            name='area',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.area'),
        ),
        migrations.AlterField(
            model_name='prognosisentry',
            name='gender',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.gender'),
        ),
        migrations.AlterField(
            model_name='prognosisentry',
            name='prognosis',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.prognosis'),
        ),
        migrations.AlterField(
            model_name='prognosisentry',
            name='year',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.year'),
        ),
        migrations.AlterField(
            model_name='rastercell',
            name='raster',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.raster'),
        ),
        migrations.AlterField(
            model_name='rastercellpopulation',
            name='cell',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.rastercell'),
        ),
        migrations.AlterField(
            model_name='rastercellpopulation',
            name='popraster',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.populationraster'),
        ),
        migrations.AlterField(
            model_name='rastercellpopulationagegender',
            name='cell',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.rastercell'),
        ),
        migrations.AlterField(
            model_name='rastercellpopulationagegender',
            name='disaggraster',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.disaggpopraster'),
        ),
        migrations.AlterField(
            model_name='rastercellpopulationagegender',
            name='gender',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.gender'),
        ),
        migrations.AlterField(
            model_name='scenariocapacity',
            name='scenario',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.scenario'),
        ),
        migrations.AlterField(
            model_name='scenariocapacity',
            name='status_quo',
            field=models.ForeignKey(null=True, on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, related_name='scenario_capacities', to='datentool_backend.capacity'),
        ),
        migrations.AlterField(
            model_name='scenariodemandrate',
            name='scenario',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.scenario'),
        ),
        migrations.AlterField(
            model_name='scenarioplace',
            name='scenario',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.scenario'),
        ),
        migrations.AlterField(
            model_name='scenarioplace',
            name='status_quo',
            field=models.ForeignKey(null=True, on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, related_name='scenario_places', to='datentool_backend.place'),
        ),
        migrations.AlterField(
            model_name='service',
            name='infrastructure',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.infrastructure'),
        ),
        migrations.AlterField(
            model_name='wmslayer',
            name='group',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.layergroup'),
        ),
    ]
