# Generated by Django 3.2.4 on 2022-01-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0042_auto_20220111_1215'),
        ('datentool_backend', '0042_auto_20220111_2102'),
    ]

    operations = [
    ]
