# Generated by Django 3.2.6 on 2022-01-12 17:37

import datentool_backend.utils.protect_cascade
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0043_merge_0042_auto_20220111_1215_0042_auto_20220111_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='populationentry',
            name='age',
        ),
        migrations.AddField(
            model_name='populationentry',
            name='age_group',
            field=models.ForeignKey(default=1, on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.agegroup'),
            preserve_default=False,
        ),
    ]
