# Generated by Django 3.2.11 on 2022-01-14 17:51

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0044_auto_20220112_1837'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Old table name from checking with sqlmigrate, new table
                # name from InfrastructureAccess._meta.db_table.
                migrations.RunSQL(
                    sql='ALTER TABLE datentool_backend_infrastructure_accessible_by RENAME TO datentool_backend_infrastructureaccess',
                    reverse_sql='ALTER TABLE datentool_backend_infrastructureaccess RENAME TO datentool_backend_infrastructure_accessible_by',
                  ),
              ],
            state_operations=[
                migrations.CreateModel(
                    name='InfrastructureAccess',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.infrastructure')),
                        ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.profile')),
                    ],
                ),
                migrations.AlterField(
                    model_name='infrastructure',
                    name='accessible_by',
                    field=models.ManyToManyField(blank=True, related_name='infrastructure_accessible_by', through='datentool_backend.InfrastructureAccess', to='datentool_backend.Profile'),
                ),
              ],
          ),
        migrations.AddField(
            model_name='infrastructureaccess',
            name='allow_sensitive_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placefield',
            name='sensitive',
            field=models.BooleanField(default=False),
        ),
      ]
