# Generated by Django 3.2.8 on 2022-01-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0045_auto_20220114_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='service_capacity',
            field=models.ManyToManyField(blank=True, related_name='place_services', through='datentool_backend.Capacity', to='datentool_backend.Service'),
        ),
    ]
