# Generated by Django 3.2.8 on 2022-01-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0046_place_service_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity',
            name='capacity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='from_year',
            field=models.IntegerField(default=0),
        ),
    ]
