# Generated by Django 3.2.11 on 2022-01-17 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0047_auto_20220117_1311'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='capacity',
            unique_together={('place', 'service', 'from_year')},
        ),
    ]
