# Generated by Django 3.2.11 on 2022-01-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0048_alter_capacity_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacity',
            name='to_year',
            field=models.IntegerField(default=99999999),
        ),
    ]
