# Generated by Django 3.2.8 on 2022-01-18 11:01

import datentool_backend.utils.protect_cascade
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0049_capacity_to_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScenarioCapacity',
        ),
        migrations.AddField(
            model_name='capacity',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.scenario'),
        ),

    ]
