# Generated by Django 3.2.8 on 2022-01-18 16:10

import datentool_backend.utils.protect_cascade
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0051_alter_capacity_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScenarioPlace',
        ),
        migrations.AddField(
            model_name='place',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.scenario'),
        ),

    ]
