# Generated by Django 3.2.5 on 2022-01-18 19:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0052_auto_20220118_1710'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Old table name from checking with sqlmigrate, new table
                # name from InfrastructureAccess._meta.db_table.
                migrations.RunSQL(
                    sql='ALTER TABLE datentool_backend_place ALTER COLUMN geom TYPE geometry(POINT, 3857) USING st_transform(geom::geometry, 3857)',
                    reverse_sql='ALTER TABLE datentool_backend_place ALTER COLUMN geom TYPE geography(POINT) USING st_transform(geom, 4326)::geography',
                  ),
                migrations.RunSQL(
                    sql='ALTER TABLE datentool_backend_area ALTER COLUMN geom TYPE geometry(MULTIPOLYGON, 3857) USING st_transform(geom::geometry, 3857)',
                    reverse_sql='ALTER TABLE datentool_backend_area ALTER COLUMN geom TYPE geography(MULTIPOLYGON) USING st_transform(geom, 4326)::geography',
                  ),
                migrations.RunSQL(
                    sql='ALTER TABLE datentool_backend_stop ALTER COLUMN geom TYPE geometry(POINT, 3857) USING st_transform(geom::geometry, 3857)',
                    reverse_sql='ALTER TABLE datentool_backend_stop ALTER COLUMN geom TYPE geography(POINT) USING st_transform(geom, 4326)::geography',
                  ),
                migrations.RunSQL(
                    sql='ALTER TABLE datentool_backend_rastercell ALTER COLUMN pnt TYPE geometry(POINT, 3857) USING st_transform(pnt::geometry, 3857)',
                    reverse_sql='ALTER TABLE datentool_backend_rastercell ALTER COLUMN pnt TYPE geography(POINT) USING st_transform(pnt, 4326)::geography',
                  ),
                migrations.RunSQL(
                    sql='ALTER TABLE datentool_backend_rastercell ALTER COLUMN poly TYPE geometry(POLYGON, 3857) USING st_transform(poly::geometry, 3857)',
                    reverse_sql='ALTER TABLE datentool_backend_rastercell ALTER COLUMN poly TYPE geography(POLYGON) USING st_transform(poly, 4326)::geography',
                  ),
                migrations.RunSQL(
                    sql='ALTER TABLE datentool_backend_projectsetting ALTER COLUMN project_area TYPE geometry(MULTIPOLYGON, 3857) USING st_transform(project_area::geometry, 3857)',
                    reverse_sql='ALTER TABLE datentool_backend_projectsetting ALTER COLUMN project_area TYPE geography(MULTIPOLYGON) USING st_transform(project_area, 4326)::geography',
                  ),
                ],

            state_operations=[
                migrations.AlterField(
                    model_name='place',
                    name='geom',
                    field=django.contrib.gis.db.models.fields.PointField(srid=3857),
                ),
                migrations.AlterField(
                    model_name='area',
                    name='geom',
                    field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857),
                ),
                migrations.AlterField(
                    model_name='stop',
                    name='geom',
                    field=django.contrib.gis.db.models.fields.PointField(srid=3857),
                ),
                migrations.AlterField(
                    model_name='rastercell',
                    name='poly',
                    field=django.contrib.gis.db.models.fields.PolygonField(srid=3857),
                ),
                migrations.AlterField(
                    model_name='rastercell',
                    name='pnt',
                    field=django.contrib.gis.db.models.fields.PointField(srid=3857),
                ),
                migrations.AlterField(
                    model_name='projectsetting',
                    name='project_area',
                    field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3857),
                ),
            ]
        )
    ]
