# Generated by Django 3.2.4 on 2022-01-20 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0053_alter_place_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arealevel',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='layer',
        ),
        migrations.AddField(
            model_name='arealevel',
            name='symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datentool_backend.mapsymbol'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datentool_backend.mapsymbol'),
        ),
        migrations.AlterField(
            model_name='arealevel',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='arealevel',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datentool_backend.source'),
        ),
        migrations.DeleteModel(
            name='InternalWFSLayer',
        ),
    ]
