# Generated by Django 3.2.4 on 2022-01-20 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0055_auto_20220120_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arealevel',
            name='source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datentool_backend.source'),
        ),
        migrations.AlterField(
            model_name='arealevel',
            name='symbol',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datentool_backend.mapsymbol'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='symbol',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datentool_backend.mapsymbol'),
        ),
    ]
