# Generated by Django 3.2.4 on 2022-01-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0056_auto_20220120_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='settings',
            field=models.JSONField(default=dict),
        ),
    ]
