# Generated by Django 3.2.11 on 2022-01-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0056_auto_20220120_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='is_default',
            field=models.BooleanField(null=True),
        ),
    ]
