# Generated by Django 3.2.11 on 2022-01-21 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0057_year_is_default'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScenarioDemandRate',
        ),
    ]
