# Generated by Django 3.2.11 on 2022-01-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0058_delete_scenariodemandrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='demand_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='demand_name',
            field=models.TextField(null=True),
        ),
    ]
