# Generated by Django 3.2.11 on 2022-01-21 18:18

import datentool_backend.utils.protect_cascade
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0060_auto_20220121_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandrate',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.gender'),
            preserve_default=False,
        ),
    ]
