# Generated by Django 3.2.4 on 2022-01-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0057_profile_settings'),
        ('datentool_backend', '0061_demandrate_gender'),
    ]

    operations = [
    ]
