# Generated by Django 3.2.11 on 2022-01-25 21:23

import datentool_backend.base
import datentool_backend.utils.protect_cascade
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0062_merge_0057_profile_settings_0061_demandrate_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('classname', models.TextField(unique=True)),
                ('description', models.TextField()),
            ],
            bases=(datentool_backend.base.NamedModel, models.Model),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='capacity',
            field=models.FloatField(default=1),
        ),
        migrations.CreateModel(
            name='IndicatorTypeFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('field_type', models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.fieldtype')),
                ('indicator_type', models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.indicatortype')),
            ],
        ),
        migrations.AddField(
            model_name='indicatortype',
            name='parameters',
            field=models.ManyToManyField(through='datentool_backend.IndicatorTypeFields', to='datentool_backend.FieldType'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='indicator_type',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.indicatortype'),
        ),
    ]
