# Generated by Django 3.2.11 on 2022-01-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0063_auto_20220125_2223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndicatorTypeFields',
            new_name='IndicatorTypeField',
        ),
    ]
