# Generated by Django 3.2.11 on 2022-01-29 16:00

import datentool_backend.utils.protect_cascade
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0065_arealevel_label_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rastercellpopulationagegender',
            name='age',
        ),
        migrations.AddField(
            model_name='rastercellpopulationagegender',
            name='age_group',
            field=models.ForeignKey(default=1, on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.agegroup'),
            preserve_default=False,
        ),
    ]
