# Generated by Django 3.2.11 on 2022-02-01 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0066_auto_20220129_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_cell_of_area', models.FloatField()),
                ('share_area_of_cell', models.FloatField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.area')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.rastercellpopulation')),
            ],
        ),
        migrations.AddField(
            model_name='rastercellpopulation',
            name='area',
            field=models.ManyToManyField(through='datentool_backend.AreaCell', to='datentool_backend.Area'),
        ),
    ]
