# Generated by Django 3.2.11 on 2022-02-02 10:01

import datentool_backend.utils.protect_cascade
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0067_auto_20220201_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatortype',
            name='category',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='parameters',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='service',
            field=models.ForeignKey(null=True, on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.service'),
        ),
    ]
