# Generated by Django 3.2.11 on 2022-02-02 21:45

import datentool_backend.utils.protect_cascade
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0068_auto_20220202_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prognosis',
            name='raster',
        ),
        migrations.AddField(
            model_name='population',
            name='prognosis',
            field=models.ForeignKey(null=True, on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.prognosis'),
        ),
    ]
