# Generated by Django 3.2.11 on 2022-02-02 22:46

import datentool_backend.utils.protect_cascade
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0069_auto_20220202_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='population',
            name='raster',
        ),
        migrations.RemoveField(
            model_name='rastercellpopulationagegender',
            name='disaggraster',
        ),
        migrations.RemoveField(
            model_name='rastercellpopulationagegender',
            name='year',
        ),
        migrations.AddField(
            model_name='population',
            name='popraster',
            field=models.ForeignKey(null=True, on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.populationraster'),
        ),
        migrations.AddField(
            model_name='rastercellpopulationagegender',
            name='population',
            field=models.ForeignKey(null=True, on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.population'),
        ),
        migrations.DeleteModel(
            name='DisaggPopRaster',
        ),
    ]
