# Generated by Django 3.2.11 on 2022-02-03 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0071_remove_population_area_level'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[('UPDATE datentool_backend_population SET popraster_id = %s;', [1])],
            reverse_sql=[('UPDATE datentool_backend_population SET popraster_id = NULL;', None)]
            ),
        migrations.RunSQL(
            sql=[('INSERT INTO datentool_backend_population (year_id, prognosis_id, popraster_id) SELECT DISTINCT pe.year_id, pe.prognosis_id, %s FROM datentool_backend_prognosisentry pe;', [1])],
            reverse_sql=[('DELETE FROM datentool_backend_population WHERE prognosis_id IS NOT NULL;', None)]
            ),
        migrations.RunSQL(
            sql=[('''
            INSERT INTO datentool_backend_populationentry
            ("value", area_id, gender_id, population_id, age_group_id)
            SELECT
            pe.value, pe.area_id, pe.gender_id, p.id AS population_id, pe.agegroup_id
            FROM datentool_backend_prognosisentry pe,
            datentool_backend_population p
            WHERE pe.prognosis_id = p.prognosis_id
            AND pe.year_id = p.year_id;''', None)],
            reverse_sql=[('''
            INSERT INTO datentool_backend_prognosisentry
            ("value", agegroup_id, area_id, gender_id, prognosis_id, year_id)
            SELECT pe."value", pe.age_group_id, pe.area_id, pe.gender_id, p.prognosis_id, p.year_id
            FROM datentool_backend_populationentry pe,
            datentool_backend_population p
            WHERE pe.population_id = p.id
            AND p.prognosis_id IS NOT NULL;
            ''', None)]
            ),
        migrations.DeleteModel(
            name='PrognosisEntry',
        ),
    ]
