# Generated by Django 3.2.11 on 2022-02-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0072_delete_prognosisentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatortype',
            name='userdefined',
            field=models.BooleanField(default=True),
        ),
    ]
