# Generated by Django 3.2.11 on 2022-02-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0067_auto_20220131_2155'),
        ('datentool_backend', '0073_indicatortype_userdefined'),
    ]

    operations = [
    ]
