# Generated by Django 3.2.11 on 2022-02-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0074_merge_20220213_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arealevel',
            name='label_field',
        ),
        migrations.AlterField(
            model_name='areafield',
            name='is_label',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='areafield',
            unique_together={('area_level', 'name'), ('area_level', 'is_label')},
        ),
    ]
