# Generated by Django 3.2.11 on 2022-02-13 18:50

from django.db import migrations, models
import datentool_backend


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0074_merge_20220213_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fclass',
            old_name='classification',
            new_name='ftype',
        ),
        migrations.RenameField(
            model_name='fieldtype',
            old_name='field_type',
            new_name='ftype',
        ),
        migrations.CreateModel(
            name='AreaField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('is_label', models.BooleanField(default=None, null=True)),
                ('area_level', models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.arealevel')),
                ('field_type', models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.fieldtype')),
            ],
            options={
                'unique_together': {('area_level', 'name')},
            },
            bases=(datentool_backend.base.DatentoolModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AreaAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_value', models.TextField(null=True)),
                ('num_value', models.FloatField(null=True)),
                ('area', models.ForeignKey(on_delete=models.deletion.CASCADE, to='datentool_backend.area')),
                ('class_value', models.ForeignKey(null=True, on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.fclass')),
                ('field', models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.areafield')),
            ],
            options={
                'unique_together': {('area', 'field')},
            },
            bases=(datentool_backend.base.DatentoolModelMixin, datentool_backend.base.NamedModel, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='areafield',
            unique_together={('area_level', 'name'), ('area_level', 'is_label')},
        ),
        migrations.RenameField(
            model_name='placefield',
            old_name='attribute',
            new_name='name',
        ),
        migrations.AddField(
            model_name='placefield',
            name='is_label',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='placefield',
            unique_together={('infrastructure', 'name'), ('infrastructure', 'is_label')},
        ),
        migrations.CreateModel(
            name='PlaceAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_value', models.TextField(null=True)),
                ('num_value', models.FloatField(null=True)),
                ('class_value', models.ForeignKey(null=True, on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.fclass')),
                ('field', models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.placefield')),
                ('place', models.ForeignKey(on_delete=models.deletion.CASCADE, to='datentool_backend.place')),
            ],
            options={
                'unique_together': {('place', 'field')},
            },
            bases=(datentool_backend.base.DatentoolModelMixin, datentool_backend.base.NamedModel, models.Model),
        ),
    ]
