# Generated by Django 3.2.11 on 2022-02-13 20:44

import datentool_backend.base
import datentool_backend.utils.protect_cascade
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0075_auto_20220213_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placefield',
            old_name='attribute',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='place',
            name='attributes',
        ),
        migrations.AddField(
            model_name='placefield',
            name='is_label',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='placefield',
            unique_together={('infrastructure', 'name'), ('infrastructure', 'is_label')},
        ),
        migrations.CreateModel(
            name='PlaceAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_value', models.TextField(null=True)),
                ('num_value', models.FloatField(null=True)),
                ('class_value', models.ForeignKey(null=True, on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.fclass')),
                ('field', models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.areafield')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.place')),
            ],
            options={
                'unique_together': {('place', 'field')},
            },
            bases=(datentool_backend.base.DatentoolModelMixin, datentool_backend.base.NamedModel, models.Model),
        ),
    ]
