# Generated by Django 3.2.4 on 2022-02-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0076_convert_area_placeattributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningprocess',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
