# Generated by Django 3.2.11 on 2022-02-13 21:01

import datentool_backend.utils.protect_cascade
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0076_auto_20220213_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeattribute',
            name='field',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.placefield'),
        ),
    ]
