# Generated by Django 3.2.4 on 2022-03-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0077_planningprocess_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningprocess',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
