# Generated by Django 3.2.4 on 2022-03-01 11:22

import datentool_backend.utils.protect_cascade
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0078_auto_20220301_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='prognosis',
            field=models.ForeignKey(null=True, on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, to='datentool_backend.prognosis'),
        ),
    ]
