# Generated by Django 3.2.4 on 2022-03-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0079_alter_scenario_prognosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatortype',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='indicatortypefield',
            name='field_type',
        ),
        migrations.RemoveField(
            model_name='indicatortypefield',
            name='indicator_type',
        ),
        migrations.AddField(
            model_name='service',
            name='direction_way_relationship',
            field=models.IntegerField(choices=[(1, 'To'), (2, 'From')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='facility_article',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='facility_plural_unit',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='facility_singular_unit',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Indicator',
        ),
        migrations.DeleteModel(
            name='IndicatorType',
        ),
        migrations.DeleteModel(
            name='IndicatorTypeField',
        ),
    ]
