# Generated by Django 3.2.4 on 2022-03-07 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0077_auto_20220302_1650'),
        ('datentool_backend', '0081_auto_20220304_1558'),
    ]

    operations = [
    ]
