# Generated by Django 3.2.4 on 2022-03-09 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0082_merge_0077_auto_20220302_1650_0081_auto_20220304_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prognosis',
            name='years',
        ),
    ]
