# Generated by Django 3.2.4 on 2022-03-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0083_remove_prognosis_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='arealevel',
            name='is_statistic_level',
            field=models.BooleanField(null=True, unique=True),
        ),
    ]
