# Generated by Django 3.2.4 on 2022-03-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0084_arealevel_is_statistic_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arealevel',
            name='is_statistic_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='demandrateset',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='modevariant',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prognosis',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
