# Generated by Django 3.2.4 on 2022-03-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0085_auto_20220317_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='demand_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='demand_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='facility_article',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='facility_plural_unit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='facility_singular_unit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
