# Generated by Django 3.2.11 on 2022-03-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0086_auto_20220325_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='areafield',
            name='is_key',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='areafield',
            unique_together={('area_level', 'is_label'), ('area_level', 'name'), ('area_level', 'is_key')},
        ),
    ]
