# Generated by Django 3.2.11 on 2022-03-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0087_auto_20220326_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='is_prognosis',
            field=models.BooleanField(default=False),
        ),
    ]
