# Generated by Django 3.2.11 on 2022-03-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0088_year_is_prognosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
