# Generated by Django 3.2.12 on 2022-03-30 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0089_alter_year_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsetting',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='projectsetting',
            name='start_year',
        ),
    ]
