# Generated by Django 3.2.12 on 2022-04-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0090_auto_20220330_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='arealevel',
            name='is_default_pop_level',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='BaseDataSetting',
        ),
    ]
