# Generated by Django 3.2.12 on 2022-04-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0093_remove_source_id_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='capacity_plural_unit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='capacity_singular_unit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='demand_plural_unit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='demand_singular_unit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='direction_way_relationship',
            field=models.IntegerField(choices=[(1, 'To'), (2, 'From')], default=1),
        ),
        migrations.AlterField(
            model_name='service',
            name='has_capacity',
            field=models.BooleanField(default=True),
        ),
    ]
