# Generated by Django 3.2.12 on 2022-04-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0094_auto_20220406_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
