# Generated by Django 3.2.12 on 2022-04-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0095_alter_source_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='is_real',
            field=models.BooleanField(default=False),
        ),
    ]
