# Generated by Django 3.2.12 on 2022-04-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0097_area_is_cut'),
    ]

    operations = [
        migrations.AddField(
            model_name='arealevel',
            name='is_pop_level',
            field=models.BooleanField(default=False),
        ),
    ]
