# Generated by Django 3.2.12 on 2022-04-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0098_arealevel_is_pop_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandrateset',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='demand_type',
            field=models.IntegerField(choices=[(1, 'Quota'), (2, 'Frequency'), (3, 'Uniform')], default=1),
        ),
    ]
