# Generated by Django 3.2.12 on 2022-04-28 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0099_auto_20220428_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandrate',
            name='age_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.agegroup'),
        ),
        migrations.AlterField(
            model_name='demandrate',
            name='demand_rate_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.demandrateset'),
        ),
        migrations.AlterField(
            model_name='demandrate',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.gender'),
        ),
        migrations.AlterField(
            model_name='demandrate',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.year'),
        ),
    ]
