# Generated by Django 3.2.12 on 2022-05-05 09:42

import datentool_backend.utils.protect_cascade
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0100_auto_20220428_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popstatistic',
            name='year',
            field=models.ForeignKey(on_delete=datentool_backend.utils.protect_cascade.PROTECT_CASCADE, related_name='statistics', to='datentool_backend.year'),
        ),
    ]
