# Generated by Django 3.2.12 on 2022-05-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0101_alter_popstatistic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='prognosis',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
