# Generated by Django 3.2.11 on 2022-05-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0102_prognosis_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='populationraster',
            name='filename',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='populationraster',
            name='srid',
            field=models.IntegerField(default=3035),
        ),
    ]
