# Generated by Django 3.2.12 on 2022-05-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0103_auto_20220507_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='populationraster',
            name='year',
        ),
    ]
