# Generated by Django 3.2.4 on 2022-05-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0104_remove_populationraster_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtype',
            name='is_preset',
            field=models.BooleanField(default=False),
        ),
    ]
