# Generated by Django 3.2.12 on 2022-05-18 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datentool_backend', '0105_fieldtype_is_preset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fclass',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='fclass',
            name='ftype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datentool_backend.fieldtype'),
        ),
        migrations.AlterField(
            model_name='placefield',
            name='unit',
            field=models.TextField(blank=True, default=''),
        ),
    ]
